### PR TITLE
Patch-01

### PR DESCRIPTION
**Pull request by lillac**

### CODE REVIEW

**Comment by AGingerWhoCodes** [comment]
Thanks lillac! - A Wild Potato

**Comment by AGingerWhoCodes** [comment]
Thanks! But how do I add these changes to he original? Or is that not possible.

**Comment by AGingerWhoCodes** [comment]
I can't make a new file for just the code, help!

**Comment by lillac** [comment]
Accept my pull request, that'll join patch-1 to the master branch then
delete the files that were originally in the master. And I don't know what
you mean by you can't make a new file for "just the code." If you're trying
to make a file in patch-1 it may not work as but it should.

**Pull request merged**
